"""empty message

Revision ID: af52c7429cb3
Revises: 78e88eb622b5
Create Date: 2019-05-19 14:12:08.964654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af52c7429cb3'
down_revision = '78e88eb622b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'blog', ['id'])
    op.create_unique_constraint(None, 'poll', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'poll', type_='unique')
    op.drop_constraint(None, 'blog', type_='unique')
    # ### end Alembic commands ###
