"""blogs table

Revision ID: 48f91eb58545
Revises: d04f041b4c0f
Create Date: 2019-03-17 20:31:36.929277

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '48f91eb58545'
down_revision = 'd04f041b4c0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blogs',
    sa.Column('stratechery', sa.Boolean(), nullable=True),
    sa.Column('startupboy', sa.Boolean(), nullable=True),
    sa.Column('bryan_caplan_econlib', sa.Boolean(), nullable=True),
    sa.Column('marginal_revolution', sa.Boolean(), nullable=True),
    sa.Column('ribbonfarm', sa.Boolean(), nullable=True),
    sa.Column('melting_asphalt', sa.Boolean(), nullable=True),
    sa.Column('overcoming_bias', sa.Boolean(), nullable=True),
    sa.Column('elaine_ou', sa.Boolean(), nullable=True),
    sa.Column('eugene_wei', sa.Boolean(), nullable=True),
    sa.Column('meaningness', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.drop_column('user', 'blogs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('blogs', sqlite.JSON(), nullable=True))
    op.drop_table('blogs')
    # ### end Alembic commands ###
