"""empty message

Revision ID: 4a4cb3a926e0
Revises: d5d197d928b0
Create Date: 2019-03-17 08:02:24.039667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a4cb3a926e0'
down_revision = 'd5d197d928b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('blogs', sa.JSON(), nullable=True))
    op.drop_index('ix_user_startupboy', table_name='user')
    op.drop_index('ix_user_stratechery', table_name='user')
    op.drop_column('user', 'stratechery')
    op.drop_column('user', 'startupboy')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('startupboy', sa.BOOLEAN(), nullable=True))
    op.add_column('user', sa.Column('stratechery', sa.BOOLEAN(), nullable=True))
    op.create_index('ix_user_stratechery', 'user', ['stratechery'], unique=False)
    op.create_index('ix_user_startupboy', 'user', ['startupboy'], unique=False)
    op.drop_column('user', 'blogs')
    # ### end Alembic commands ###
