"""empty message

Revision ID: 50785c161142
Revises: 48f91eb58545
Create Date: 2019-03-17 20:40:46.150606

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '50785c161142'
down_revision = '48f91eb58545'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'blogs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('blogs', sqlite.JSON(), nullable=True))
    # ### end Alembic commands ###
