"""empty message

Revision ID: ace89e5069f5
Revises: 50785c161142
Create Date: 2019-03-17 20:45:21.877747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ace89e5069f5'
down_revision = '50785c161142'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('kindle_email', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_kindle_email'), 'user', ['kindle_email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('blogs',
    sa.Column('stratechery', sa.Boolean(), nullable=True),
    sa.Column('startupboy', sa.Boolean(), nullable=True),
    sa.Column('bryan_caplan_econlib', sa.Boolean(), nullable=True),
    sa.Column('marginal_revolution', sa.Boolean(), nullable=True),
    sa.Column('ribbonfarm', sa.Boolean(), nullable=True),
    sa.Column('melting_asphalt', sa.Boolean(), nullable=True),
    sa.Column('overcoming_bias', sa.Boolean(), nullable=True),
    sa.Column('elaine_ou', sa.Boolean(), nullable=True),
    sa.Column('eugene_wei', sa.Boolean(), nullable=True),
    sa.Column('meaningness', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blogs')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_kindle_email'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
