"""empty message

Revision ID: d5d197d928b0
Revises: 59ae13ca7668
Create Date: 2019-03-17 00:06:17.443633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5d197d928b0'
down_revision = '59ae13ca7668'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('startupboy', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('stratechery', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_user_startupboy'), 'user', ['startupboy'], unique=False)
    op.create_index(op.f('ix_user_stratechery'), 'user', ['stratechery'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_stratechery'), table_name='user')
    op.drop_index(op.f('ix_user_startupboy'), table_name='user')
    op.drop_column('user', 'stratechery')
    op.drop_column('user', 'startupboy')
    # ### end Alembic commands ###
